whitelist: [base, extra, mod]

base:
    # bundle magic number
    stock_num: 4000
    # 数据源所存储的文件路径
    data_bundle_path: /Users/scrat/bundle_old
    # 回测起始日期，str类型
    start_date: "20170101"
    # 回测结束日期(如果是实盘，则忽略该配置)，str类型
    end_date: "20181130"
    # 运行类型，`b` 为回测，`p` 为模拟交易, `r` 为实盘交易。
    run_type: b
    # 目前支持 `1d` (日线回测) 和 `1m` (分钟线回测)，如果要进行分钟线，请注意是否拥有对应的数据源，目前开源版本是不提供对应的数据源的。
    frequency: 1d
    # Benchmark，如果不设置，默认没有基准参照。
    benchmark: 000905.SH
    # 默认开启 resume 功能, 在结束的时候，生成一个pickle文件，保存strategyContext. 所以必须有persist_mod的支持，不然resume会失效。
    resume_mode: False

strategy:
    # 默认使用的池子
    pool_name: pool_01
    # 通过该参数可以将预定义变量传入 `context` 内。
    context_vars: 
        pool_name: pool_01
        rebalance_oddlots: True 
        alpha_file: configure/f.csv
        risk_file: configure/BarraStyle.csv
        forward_period: 5
        rolling_window: 200
        ff_name: wf_20181102_f
        est_open_price: trade_price_0935_1000_aft
        est_close_price: trade_price_0935_1000_aft
        verbose: True
        #        flow_config:
        #            est_flow_name: est
        #            pred_flow_name: pred_20180830
        #            optim_flow_name: optim_v2_20180830

extra:
    # 选择日期的输出等级，有 `verbose` | `debug` | `info` | `warning` | `error` 等选项，您可以通过设置 `verbose` 来查看最详细的日志，
    # 或者设置 `error` 只查看错误级别的日志输出
    log_level: warning
    log_file: ./log

# 全局的module, 及默认
mod:
    # 载入 Account 和 Position Model
    accounts:
        enabled: False
        total_cash: 10000000
    # 持久化 和 生成保存运行状态
    persist:
        enabled: False
        report_save_path: report
        content: ["trades", "orders", "holdings", "net_values", "save"]
    broker:
        enabled: False
        match_mode: trade_price_0935_1000
        reader: common
    simulation:
        enabled: True

